# Digit Recognizer

by serdar biçici

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split


In [2]:
# read the train file (digits image pixels) and the labels, construct a model and train it

# read the train file
df = pd.read_csv('train.csv')

# split the data into features and labels
X = df.drop('label', axis=1)
y = df['label']

# split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# scale the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# train the model
from sklearn.svm import SVC
model = SVC()
model.fit(X_train, y_train)

# evaluate the model
from sklearn.metrics import classification_report, confusion_matrix
predictions = model.predict(X_test)
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))



[[801   0   3   0   1   3   7   0   1   0]
 [  0 892   8   1   1   1   1   2   2   1]
 [  2   6 820   3   4   0   4   2   5   0]
 [  1   3  11 885   0  11   0   9  12   5]
 [  1   0  11   0 805   1   5   4   0  12]
 [  2   1   8  14   1 663  10   1   2   0]
 [  5   1  11   0   0   6 760   0   2   0]
 [  0   2  12   3   5   2   0 854   1  14]
 [  1   4   9  10   4  10   4   2 789   2]
 [  2   2   7  12   7   3   0  19   4 782]]
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       816
           1       0.98      0.98      0.98       909
           2       0.91      0.97      0.94       846
           3       0.95      0.94      0.95       937
           4       0.97      0.96      0.97       839
           5       0.95      0.94      0.95       702
           6       0.96      0.97      0.96       785
           7       0.96      0.96      0.96       893
           8       0.96      0.94      0.95       835
           9       0.96     

In [4]:
# now, read the test file and predict the labels in format of ImageId,Label 1,0 in a csv file

# read the test file
test = pd.read_csv('test.csv')

# scale the test data
test = scaler.transform(test)

# predict the labels
predictions = model.predict(test)


# write the predictions to a csv file
submission = pd.DataFrame({'ImageId': range(1, len(predictions)+1), 'Label': predictions})
submission.to_csv('submission.csv', index=False)




ValueError: Found input variables with inconsistent numbers of samples: [8400, 28000]